# Generated by Django 2.1.3 on 2019-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190206_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='answer',
            field=models.CharField(blank=True, default='please answer', max_length=250, null=True),
        ),
    ]
